language: go
go:
- 1.12.x

go_import_path: github.com/segmentio/terraform-docs

sudo: false

before_install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    go get github.com/Masterminds/glide;
  fi

install:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    glide install;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi

notifications:
  email: false
